# OCI CI test

name: OCI CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  tenancy-namespace:
    runs-on: ubuntu-latest
    name: Build and redeploy 
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: create OKE cluster access
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: 'oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OKE_CLUSTER_OCID }} --region ${{ secrets.OKE_REGION }} --token-version 2.0.0  --kube-endpoint PUBLIC_ENDPOINT'
          silent: false
        
